/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menuBasedatos;

import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.omg.CosNaming.IstringHelper;
import java.awt.*;
import java.awt.image.*;
import java.io.FileOutputStream;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.net.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import static menuBasedatos.MenuBasedatos.con;
import static menuBasedatos.MenuBasedatos.st;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import static menuBasedatos.MenuBasedatos.con;

/**
 *
 * @author tarde
 */
public class CocheDatos extends javax.swing.JFrame {

    ArrayList<Coche1> coches;

    /**
     * Creates new form Tabla
     */
    public CocheDatos(ArrayList coches) {
        initComponents();
        this.saveCoches(coches);
    }

    void saveCoches(ArrayList coches) {

        this.coches = coches;
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Matricula");
        model.addColumn("Marca");
        model.addColumn("Model");
        model.addColumn("Motor");
        try {
           
            //Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/almacen", "root", "");
            ResultSet rs = null;
            String sql3 = "select * from coches";
            st = con.createStatement();
            rs = st.executeQuery(sql3);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});

            }
        } catch (SQLException sqe) {
        }

        jTable1.setModel(model);

    }

    void desearizar(Coche1 c) {
        /*FileOutputStream fos;
        ObjectOutputStream oos;
        try {
            fos = new FileOutputStream("coches.dat");
            oos = new ObjectOutputStream(fos);
            oos.writeObject(coches);

        } catch (Exception e) {
            System.out.println("No se puede crear el fichero");
        }
        //saveCoches(coches);
         */
        try {
            String sql1 = "delete from coches where matricula = '"+c.matricula+"'";
            System.out.println(sql1);
            con = DriverManager.getConnection("jdbc:mysql://localhost/almacen", "root", "");

            st = con.createStatement();

            int n = st.executeUpdate(sql1);

            if (n == 1) {
                System.out.println("registro borrado");
            } else if (n == -1) {
                System.out.println("registros borrados");
            } else {
                System.out.println("registro no borrado");
            }

        } catch (SQLException sqe) {
            System.out.println("NooDo!");
        }
        saveCoches(coches);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matricula", "Marca", "Model", "Motor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("BORRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
           
            //Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/almacen", "root", "");
            ResultSet rs = null;
            String sql3 = "select * from coches";
            st = con.createStatement();
            rs = st.executeQuery(sql3);
            while (rs.next()) {
                coches.add(new Coche1(rs.getString(1), rs.getString(2), rs.getString(3),Integer.parseInt(rs.getString(4))));

            }
        } catch (SQLException sqe) {
        }
        int r = jTable1.getSelectedRow();
        ArrayList c = new ArrayList();
        if (r > -1) {

            for (int i = 0; i < coches.size(); i++) {
                if (i != r) {
                    Coche1 cc = (Coche1) coches.get(i);
                    c.add(cc);
                }else {
                    Coche1 cc = (Coche1) coches.get(i);
                    this.desearizar(cc);
                }
            }
            

        } else {
            JOptionPane.showMessageDialog(this, "Elige una coche!!");
        }
        coches = new ArrayList();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CocheDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CocheDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CocheDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CocheDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
